config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '' => 'users#index'
  get '/classes' => 'workout_times#index'

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :workout_rosters, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/studio.rb
class Studio < ApplicationRecord
  has_many :workouts
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :workout_rosters, foreign_key: 'student_id'
  has_many :workout_times, through: :workout_rosters
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :studio
  has_many :workout_times
end

app/models/workout_roster.rb
class WorkoutRoster < ApplicationRecord
  belongs_to :workout_time
  belongs_to :student, class_name: 'User', foreign_key: 'student_id'
end

app/models/workout_time.rb
class WorkoutTime < ApplicationRecord
  belongs_to :workout
  has_many :workout_rosters
  has_many :students, through: :workout_rosters

  def max_students
    workout.max_number_students
  end

  def number_of_registered_students
    students.length
  end

  def available
    max_students > number_of_registered_students
  end

  def self.available
    select{|workouttime| workouttime.max_students > workouttime.number_of_registered_students}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new; end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user_path
    else
      render :new and return
    end
  end

  def destroy
    log_out
    redirect_to ''
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index; end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      log_in(user)
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  private
  def user_params
    params.require(:user).permit(
      :first_name, 
      :last_name, 
      :username, 
      :password, 
      :password_confirmation
    )
  end

end

app/controllers/workout_rosters_controller.rb
# require 'pry'
class WorkoutRostersController < ApplicationController
  
  def new
    @workout_roster = WorkoutRoster.new
  end

  def create
    # binding.pry
    @workout_roster = WorkoutRoster.create(workout_time_id: params[:time], student_id: current_user.id)
    redirect_to classes_path
  end

end

app/controllers/workout_times_controller.rb
class WorkoutTimesController < ApplicationController

  def index
    @available_workouts = WorkoutTime.available
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workout_rosters_helper.rb
module WorkoutRostersHelper
end

app/helpers/workout_times_helper.rb
module WorkoutTimesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ClasspassClone
    
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://js.stripe.com/v3/'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  
  %body
    = yield

app/views/users/index.html.erb
<h1>Welcome to Classpass</h1>

<% if logged_in? %>
  <h1>Hi <%= current_user.first_name %> </h1>
  <%= link_to "Available Classes", classes_path %>
  <!-- Why doesn't this log out method work? -->
  <%-# link_to "Log out", session_path, method: :delete -%>
<% else %>
  <%= link_to "Register", new_user_path %>
  <%= link_to "Log In", new_session_path %>
<% end %>

app/views/users/new.html.erb
<h1> Create an account here </h1>

<%= form_for @user do |f| %>
  Username: <%= f.text_field :username %><br />
  First Name: <%= f.text_field :first_name %><br />
  Last Name: <%= f.text_field :last_name %><br />
  Password: <%= f.password_field :password %><br />
  Password Confirmation: <%= f.password_field :password_confirmation %><br />
  <%= f.submit 'Create Account' %>
<% end %>

app/views/users/show.html.erb
<h1> Welcome <%=@user.first_name%>!</h1>
<h2> Here are your upcoming classes: </h2>
<ul>
  <%@user.workout_times.each do |time| %>
    <em>Class: <%= time.workout.name %></em>
    <li>Date: <%= time.start_time.to_date %></li>
    <li>Time: <%= time.start_time.strftime("%H:%M") %></li>
  <%end%>
</ul>

app/views/workout_rosters/_form.html.erb
<% form_tag workout_rosters_path, method: :post do %>
  <%= hidden_field_tag :time, time.id %>
  <%= submit_tag 'Sign up!' %>
<% end %>

app/views/workout_rosters/new.html.erb
<h1> Are you sure you want to sign up for this class? </h1>

<%= form_for [@workout_roster] do |f| %>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/workout_times/index.html.erb
<h2> Here are available classes: </h2>
<ul>
  <%@available_workouts.each do |time| %>
    <em>Class: <%= time.workout.name %></em>
    <li>Date: <%= time.start_time.to_date %></li>
    <li>Time: <%= time.start_time.strftime("%H:%M") %></li>
    <li><%=link_to 'Sign up!', new_workout_roster_path %></li>
  <%end%>
</ul>